[package]
name = "day-04-secure-container"
version = "0.1.0"
authors = ["Smit Patel <smit@cityflo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex  = "0.3.0"