[package]
name = "day-01-the-tyranny-of-the-rocket-equation"
version = "0.1.0"
authors = ["Smit Patel <the1995captainh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
